// Copyright XiaoYao

#pragma once

#include "DiffResults.h"
#include "IAssetTypeActions.h"
#include "Editor/Kismet/Private/DiffControl.h"
#include "Runtime/Launch/Resources/Version.h"

struct FDiffResultItem;
class UEdGraph;
struct FEdGraphEditAction;

class UNarrativeAsset;
class SNarrativeDiff;

/////////////////////////////////////////////////////////////////////////////
/// FNarrativeAssetDiffControl
#if ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION < 2
class NARRATIVEEDITOR_API FNarrativeAssetDiffControl : public TDetailsDiffControl<false>
#else
class NARRATIVEEDITOR_API FNarrativeAssetDiffControl : public FDetailsDiffControl
#endif
{
public:
	FNarrativeAssetDiffControl(const UNarrativeAsset* InOldNarrativeAsset, const UNarrativeAsset* InNewNarrativeAsset, FOnDiffEntryFocused InSelectionCallback);

	virtual void GenerateTreeEntries(TArray<TSharedPtr<FBlueprintDifferenceTreeEntry>>& OutTreeEntries, TArray<TSharedPtr<FBlueprintDifferenceTreeEntry>>& OutRealDifferences) override;
};

/////////////////////////////////////////////////////////////////////////////
/// FNarrativeGraphToDiff: engine's FGraphToDiff customized to Narrative Graph
struct NARRATIVEEDITOR_API FNarrativeGraphToDiff : public TSharedFromThis<FNarrativeGraphToDiff>, IDiffControl
{
	FNarrativeGraphToDiff(class SNarrativeDiff* DiffWidget, UEdGraph* GraphOld, UEdGraph* GraphNew, const FRevisionInfo& RevisionOld, const FRevisionInfo& RevisionNew);
	virtual ~FNarrativeGraphToDiff() override;

	/** Add widgets to the differences tree */
	virtual void GenerateTreeEntries(TArray<TSharedPtr<FBlueprintDifferenceTreeEntry>>& OutTreeEntries, TArray<TSharedPtr<FBlueprintDifferenceTreeEntry>>& OutRealDifferences) override;

	UEdGraph* GetGraphOld() const { return GraphOld; };
	UEdGraph* GetGraphNew() const { return GraphNew; };

	/** Source for list view */
	TArray<TSharedPtr<FDiffResultItem>> DiffListSource;
	TSharedPtr<TArray<FDiffSingleResult>> FoundDiffs;

	/** Index of the first item in RealDifferences that was generated by this graph */
	int32 RealDifferencesStartIndex = INDEX_NONE;

private:
	FText GetToolTip() const;
	TSharedRef<SWidget> GenerateCategoryWidget() const;

	/** Called when the Newer Graph is modified*/
	void OnGraphChanged(const FEdGraphEditAction& Action) const;

	void BuildDiffSourceArray();

	class SNarrativeDiff* DiffWidget;
	UEdGraph* GraphOld;
	UEdGraph* GraphNew;

	/** Description of Old and new graph */
	FRevisionInfo RevisionOld;
	FRevisionInfo RevisionNew;

	FDelegateHandle OnGraphChangedDelegateHandle;
};
